import type { Metadata } from "next";
import "../globals.css";
import { SanityLive } from "@/sanity/lib/live";
import { inter } from "../_lib/fonts";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "News HomePage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`${inter.variable}`}>
      <Header />
      {children}
      <SanityLive />
    </main>
  );
}
